### ISSUE TITLE
CU Flasher un élément (2) : contrôles

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#10]
- vérifier que le numéro scanné est composé de 7 chiffres. En cas d'erreur, message affiché "le numéro de scan n'est pas valide. Veuillez réessayer"

- vérifier que le nom est renseigné. En cas d'erreur, message affiché "un utilisateur doit être associé au matériel"

- taille du commentaire limitée à 250 caractères. En cas d'erreur, message affiché "Le commentaire  est limité à 250 caractères"

**Comment by misbiscot** [comment]
champs obligatoire mis en place, retour d'erreur en rouge géré.
Reste la limitation pour le scan et pour le commentaire

**Comment by pom421** [comment]
ajout contrôle pour le n° Asset
