### ISSUE TITLE
CU Import : à faire dans une AsyncTask pour éviter que l'UI soit figée

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#15]
Lors de l'import, Android avertit que l'UI est resté figée pendant x frames. Cela explique par exemple pourquoi le Dialog reste figé.

cf. AsyncTask

**Comment by pom421** [comment]
- ajouter une Progress bar lors de l'import

https://guides.codepath.com/android/Handling-ProgressBars

**Comment by cmlcml2** [comment]
J'ai commencé pour juste afficher un sablier (DialogProgress) mais d’après plusieurs test j'ai l'impression que son utilisation n'est pas possible sans Thread (AsyncTask).

Je n'ai pas commit le fichier mais je te le joins si tu veux jeter un œil.

[ListeParcItemsActivity - Copie.txt](https://github.com/SEPANMOBILE/origami/files/675807/ListeParcItemsActivity.-.Copie.txt)

**Comment by cmlcml2** [comment]
04/01/17 13:36
Sauvegarde du fichier

ProgressDialog Avec spinner et buttons
[ImporterActivity - Copie.txt](https://github.com/SEPANMOBILE/origami/files/684650/ImporterActivity.-.Copie.txt)

**Comment by cmlcml2** [comment]
Ajout d'une Progressbar et import fait dans un thread
