### ISSUE TITLE
Revoir l'export CSV. Si on coche "Quote all text cells", les caractères \n devraient être prises en compte.

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#34]
Vérfier que l'importe se passe toujours bien (supprimer les " en trop si nécessaire)

**Comment by cmlcml2** [comment]
Cocher "Quote all text cells" crée quand même une nouvelle ligne dans le fichier csv.

**Comment by cmlcml2** [comment]
Modification du Wiki afin de supprimer tout les ; de chaque cellules pour récupérer correctement tout les champs.

**Comment by pom421** [comment]
Les apostrophes servent à "protéger" le contenu des passements de ligne ou des ; intempestifs.

Pour améliorer le processus, on pourra utiliser open CSV
