### ISSUE TITLE
Bug CU Détail. Changement d'orientation efface partiellement la saisie

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#36]
Si l'on passe de l'orientation portrait à paysage, on perd les modifications pour Nom, commentaire, matériel ??

**Comment by pom421** [comment]
Avec le chargement de propriétés par défaut, le comportement est légèrement différent. 
Si on crée un nouveau matériel, le nom donné dans les préférences est rempli.
Si on change ce nom et qu'on change l'orientation, le nom des préférences est à nouveau rempli.

**Comment by cmlcml2** [comment]
Resolu
