### ISSUE TITLE
CU Liste : afficher une marque pour renseigner sur le filtre utilisée

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#38]
Exemple : je clique sur "uniquement les inventoriés", il faudrait avoir une coche ensuite sur cette ligne

**Comment by cmlcml2** [comment]
Utilisation d'un tableau de boolean pour chaque filtre, la valeur true ou false change en fonction du filtre sélectionné(quand on clique dessus) afin de faire un setText pour rajouter une "marque" sur le filtre utilisé.
L'application crash.
Le code n'a pas été commit.
Je n'ai pas trouvé d'autre moyen pour le moment mais je pense que ce code fait trop "bricolage" pour être laissé.
