### ISSUE TITLE
Bug visuel : CU Liste. Le FAB devrait être toujours en bas même si la liste est petite

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#39]

**Comment by cmlcml2** [comment]
-Ajout d'un relativeLayout qui englobe tout.
-Ajout d'un LinearLayout qui englobe l'ActionBar et la liste

Je regarde pour mettre en place un CoodinatorLayout

**Comment by cmlcml2** [comment]
Je suis revenu au code de base. Le bug graphique du au clavier était déjà présent. 
Il suffisait juste de changer le 
layout_width
layout_height
pour que le fab reste en bas....

**Comment by cmlcml2** [comment]
Bug réglé dans AndroidManifest.
