### ISSUE TITLE
Évolution CU Courriel

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#44]
Ne plus imposer Gmail comme Activity d'envoi de courriel

**Comment by cmlcml2** [comment]
Plus compliqué que prévu : 
L'ancienne application utilisait un ACTION_SENDTO.
Origami utilise un ACTION_SEND_MULTIPLE. 
Lors de la sélection de l'application mail aucune application n'est proposée.

Le code n'a pas été comité.

**Comment by cmlcml2** [comment]
L'utilisateur a le choix d'envoyer(apps Mails) ou enregistrer(apps Cloud) les fichiers d'import avec l'application de son choix, afin de ne pas le restreindre à utiliser Gmail dans le cas où l'application ne serait pas installée ou configurée sur son appareil.
