### ISSUE TITLE
CU Détail : ajouter une popup quand le numAsset ou le numSerie est déjà affecté à un matériel

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#49]
Utiliser le même système de popup que lorsque l'utilisateur veut sortir du CU détail alors qu'il a fait des modifications qu'il n'a pas sauvé. 

Ici l'idée est de le faire à chaque fois qu'on avait le focus sur numAsset et que l'utilisateur veut en sortir. Une requête doit être faite pour savoir si ce numAsset est déjà affecté. Si c'est le cas, afficher une popup expliquant que : 
"Ce numAsset est déjà attribué, merci d'en choisir un autre en appuyant sur Annuler ou appuyer sur OK pour modifier cet élément existant".

S'il clique sur Annuler, le focus est laissé sur le numAsset et il y restera jusqu'à ce que le numAsset soit inconnu en base ou que l'utilisateur choisisse OK dans la popup. 

S'il clique sur OK, les données sont rafraîchies avec les données de ce numAsset déjà connu. 

Faire de même avec le numSerie.

**Comment by cmlcml2** [comment]
Maintenant on ne pourra jamais avoir le même numéro de série  qu'un autre item (Quand on clique sur un item de la liste ou qu'on arrive par un scan, si on change le numéro de série par un numéro de série déjà existant en base, la fiche se met à jour avec l'item correspondant à ce numéro de série.
Si cela ne convient pas, il faut supprimer la méthode numSerieEgalListener.

**Comment by cmlcml2** [comment]
Concernant le numAsset je n'ai pas de remarque, cela fonctionne.
