### ISSUE TITLE
Modifier le concept de suppression

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#55]
Supprimer un matériel ne supprime plus en base. À la place, il faut ajouter une situation dans la table ParcItem pour ce n° Asset avec l'état supprimé.

Conséquences : 

- ajout d'un filtre "Uniquement les supprimés" dans la liste
- modifier les requêtes Tous, Uniquement les inventoriés et Uniquement les non inventoriés pour ignorer les lignes portant sur des n° Asset dont la dernière situation est supprimé
- si l'on est sur le détail d'un matériel supprimé, le bouton Supprimer devient Rétablir. Les champs sont tous "disabled" à part le bouton Rétablir. En cas de clic sur ce bouton, les champs (et le bouton Sauver) deviennent modifiable. En cas de modification effectuée, on crée une nouvelle situation pour ce n° Asset en prenant bien soin de récupérer le bon état (= état de la situation juste avant la situation de suppression)

**Comment by cmlcml2** [comment]
Ajouter un "Undo" de suppression dans une snackbar.
