### ISSUE TITLE
Modifier menu

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#56]
Le menu drawer devient : 

- Liste des matériels (à la place de Inventaire)
- Gérer ma base de données (ou Gérer mes données si pas assez de place) à la place de Importer
- Scanner matériel
- Ajout manuel
- Préférences
- ici ajouter un trait pour séparer --------------------
- Aide & fonctionnalités
- À propos

**Comment by pom421** [comment]
Changer Aide & fonctionnalités en Aide
Changer l'icone des préférences. Trouver une icone plus parlante pour les préférences 

Tester les icones : 
- Liste : important device, view list
- Gérer : build
- Ajout manuel : edit
- Préférence : settings

Ajouter un lien dans la page À propros en dessous de DGFiP / SI 1G / SEPAN, "Nous contacter", qui ouvre un client mail vers notre balf bureau.si1g-annuaire-dgfip@dgfip.finances.gouv.fr

**Comment by cmlcml2** [comment]
Done
