### ISSUE TITLE
Vérifier le bon fonctionnement de l'app même en cas de destroy d'une activity

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#57]
Android peut supprimer une Activity précédente pour préserver le système (simulable via Préférences > Options développeurs > Ne pas conserver activités). 

Faire les modifications nécessaires dans le cycle de vie des activity pour que tout fonctionne.

En particulier, vérifier le clic sur le nom de la personne (dans la page de détail d'un matériel) qui doit rediriger correctement sur la liste des matériels.

**Comment by cmlcml2** [comment]
Done
