### ISSUE TITLE
Liste : rendre invisible le I dans la liste des matériels supprimés

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#58]
Ne plus rendre visible le I dans ce filtre particulier. En effet, inventorier ou désinventorier un matériel supprimé n'a pas de sens.
En base de données, il ne faut pas changer cet attribut, juste ne plus le rendre visible dans l'UI.

**Comment by cmlcml2** [comment]
Rendre invisible le  I entraine un Bug graphique sur des items qui ne sont pas supprimés.
Solution provisoire : Le I est maintenant non cliquable quand l'item est supprimé.

**Comment by cmlcml2** [comment]
Rendre invisible le  I entraine un Bug graphique sur des items qui ne sont pas supprimés.
Solution provisoire : Le I est maintenant non cliquable quand l'item est supprimé.

**Comment by cmlcml2** [comment]
Solution provisoire acceptée
