### ISSUE TITLE
Détail : clic sur nom, la recherche doit montrer le début du nom

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#60]
Si possible, mettre le curseur clignotant au début du champ de recherche plutôt qu'à la fin

Par exemple, pour le champ "JENOUDET, jacques", quand l'affichage est trop petit pour tout afficher, il doit privilégier le début plutôt que la fin.

**Comment by cmlcml2** [comment]
Clear du focus sur la barre ce qui permet de revenir au début du nom plus facilement manuellement mais pas automatiquement.

**Comment by cmlcml2** [comment]
Corrigé :                
On a accès aux "sous widgets" du widget de la searchview :  
((EditText)searchView.findViewById(android.support.v7.appcompat.R.id.**search_src_text**)).setSelection(0);
