### ISSUE TITLE
CU Détail : wording

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#63]
Changer le contenu texte en cas de N° Asset déjà existant. 

Remplacer le contenu de la popup par : 

titre : N° Asset existant
paragraphe : Le N° Asset est présent en base. Voulez-vous charger cet élément ou bien annuler pour modifier votre saisie? 

Boutons : "Annuler" et "Charger matériel"

**Comment by cmlcml2** [comment]
Done
