### ISSUE TITLE
CU Importer un fichier xls d'inventaire

### ISSUE THREAD

**Issue by pom421** [SEPANMOBILE/origami#8]
Le but est d'importer un fichier xls dans la base de données SQLite.

**Comment by pom421** [comment]
On suppose que l'utilisateur a téléchargé un fichier inventaire.csv dans la partie Downloads du téléphone.

Contrôles : 
- si le fichier inventaire.csv n'existe pas -> Toast 
- lors de l'import, si la base est non vide -> Dialogs pour confirmer ou non d'écraser les données avec le nouveau fichier

Dans un premier temps, on pourra ajouter la permission à la main, dans les préfernces Android > Application > Origami > Permissions. Ensuite, il faudra ajouter dans ImportActivity la gestion des permissions (requestPermission, etc..)

**Comment by cmlcml2** [comment]
Il faut faire attention de retirer tous les retour à la ligne de chaque cellule du fichier excel.xml avant de le convertir (sélectionner toutes les cellules, ctrl+h, crtl+j et remplacer) en .csv sinon de nouvelles lignes sont créées.
